markdown:         kramdown

# Setup
title:            Droids And Druids
description:      'Un podcast sobre ciencia ficción y fantasía'
url:              https://droidsanddruids.com
baseurl:          /

paginate:         5

social:
  twitter:        https://twitter.com/DroidsAndDruids
  instagram:      https://www.instagram.com/droidsanddruids/
  github:         https://github.com/DroidsAndDruids